# Generated by Django 3.1.7 on 2021-03-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210310_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Retailer',
        ),
    ]
