# Generated by Django 3.1.7 on 2021-03-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210311_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='retailer',
        ),
    ]
