# Generated by Django 3.1.7 on 2021-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('BOUCLAIR', 'Bouclair'), ('CRATE_&_BARREL', 'Crate & Barrel'), ('ELTE', 'ELTE'), ('EQ3', 'EQ3'), ('WAYFAIR', 'Wayfair')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
